### ISSUE TITLE
Cannot set headers and missing ressources

### ISSUE THREAD

**Issue by MyZeD** [ryanlelek/Raneto#259]
Greetings,
my problem is Raneto don't want work after version 0.14.0 (now 0.16.0, was in 0.15.0 the same).

The error-messages in the terminal are:

```
GET / 403 5.550 ms - 60
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at validateHeader (_http_outgoing.js:503:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at ServerResponse.header (/home/roman/Downloads/wiki.cavi.run/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/roman/Downloads/wiki.cavi.run/node_modules/express/lib/response.js:170:12)
    at done (/home/roman/Downloads/wiki.cavi.run/node_modules/express/lib/response.js:1004:10)
    at /home/roman/Downloads/wiki.cavi.run/node_modules/hogan-express/hogan-express.js:169:20
    at /home/roman/Downloads/wiki.cavi.run/node_modules/hogan-express/hogan-express.js:40:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3)
GET /login 304 16.119 ms - -
GET /lib/bootstrap/dist/css/bootstrap.min.css 403 0.969 ms - 32
GET /styles/raneto.css 304 2.340 ms - -
GET /styles/login-form.css 304 2.625 ms - -
GET /styles/login-style.css 304 2.644 ms - -
GET /styles/zocial.css 304 2.658 ms - -
Error: Ups. Sieht so aus als würde diese Seite nicht existieren.
GET /lib/jquery/dist/jquery.min.js 403 0.575 ms - 32
Error: Ups. Sieht so aus als würde diese Seite nicht existieren.
GET /lib/bootstrap/dist/js/bootstrap.min.js 403 1.276 ms - 32
GET /lib/jquery-backstretch/jquery.backstretch.min.js 403 1.499 ms - 32
GET /lib/sweetalert2/dist/sweetalert2.all.min.js 403 1.683 ms - 32
GET /scripts/login.js 304 0.248 ms - -
Error: Ups. Sieht so aus als würde diese Seite nicht existieren.
Error: Ups. Sieht so aus als würde diese Seite nicht existieren.
Error: Ups. Sieht so aus als würde diese Seite nicht existieren.
```
I changed the directory in:
-- node_modules/
-- content/
-- config.default.js
-- server.js
-- packages.json

The changes in the server.js are:
`var config = require('./config.default.js');`

And in the config.default.js:

```
theme_dir  : path.join(__dirname, 'node_modules', 'raneto', 'themes'),
public_dir  : path.join(__dirname, 'node_modules', 'raneto', 'themes', 'default', 'public'),
authentication_for_read: true,
locale: 'de',
searchExtraLanguages: ['en'],
```

These wasn`t the full code, but the changed lines.

**Comment by hplageman** [comment]
Did you ever figure this out?

**Comment by ryanlelek** [comment]
Question:
Was this on Windows OS?
#293 may be related in that case.

Otherwise, please send any information you have.
It's possible this was fixed in a recent version.

I'd suggest cloning the latest version of Raneto.
If it runs correctly, we'll have a starting point to compare.
If it fails... then we'll fix it :)
