### ISSUE TITLE
Raneto fails to start on Synology NAS / node 0.10

### ISSUE THREAD

**Issue by will-code-for-pizza** [ryanlelek/Raneto#282]
```
# npm version
{ raneto: '0.16.0',
  npm: '2.15.1',
  ares: '1.9.0-DEV',
  http_parser: '1.2',
  modules: '11',
  node: '0.10.48',
  openssl: '1.0.2k-fips',
  uv: '0.10.37',
  v8: '3.14.5.11',
  zlib: '1.2.8' }

# npm bugs raneto
npm ERR! Linux 3.10.105
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "bugs" "raneto"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! enoent spawn ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /volume1/web/raneto/npm-debug.log

# which npm
/usr/local/bin/npm

# which node
/usr/local/bin/node

# cat /volume1/web/raneto/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'bugs', 'raneto' ]
2 info using npm@2.15.1
3 info using node@v0.10.48
4 verbose node symlink /usr/local/bin/node
5 silly mapToRegistry name raneto
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry data { raw: 'raneto',
8 silly mapToRegistry   scope: null,
8 silly mapToRegistry   name: 'raneto',
8 silly mapToRegistry   rawSpec: '',
8 silly mapToRegistry   spec: 'latest',
8 silly mapToRegistry   type: 'tag' }
9 silly mapToRegistry uri https://registry.npmjs.org/raneto
10 verbose request uri https://registry.npmjs.org/raneto/latest
11 verbose request no auth needed
12 info attempt registry request try #1 at 14:16:48
13 verbose request id 1cf867b991a5eda2
14 http request GET https://registry.npmjs.org/raneto/latest
15 http 200 https://registry.npmjs.org/raneto/latest
16 verbose headers { date: 'Sun, 09 Dec 2018 13:16:49 GMT',
16 verbose headers   'content-type': 'application/json',
16 verbose headers   'transfer-encoding': 'chunked',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'set-cookie': [ '__cfduid=d69ea0c1b0b09b68e796139018ad51fe01544361408; expires=Mon, 09-Dec-19 13:16:48 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
16 verbose headers   'content-encoding': 'gzip',
16 verbose headers   'cf-ray': '4867bf932be3975c-FRA',
16 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
16 verbose headers   vary: 'Accept-Encoding',
16 verbose headers   server: 'cloudflare' }
17 silly get cb [ 200,
17 silly get   { date: 'Sun, 09 Dec 2018 13:16:49 GMT',
17 silly get     'content-type': 'application/json',
17 silly get     'transfer-encoding': 'chunked',
17 silly get     connection: 'keep-alive',
17 silly get     'set-cookie': [ '__cfduid=d69ea0c1b0b09b68e796139018ad51fe01544361408; expires=Mon, 09-Dec-19 13:16:48 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
17 silly get     'content-encoding': 'gzip',
17 silly get     'cf-ray': '4867bf932be3975c-FRA',
17 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
17 silly get     vary: 'Accept-Encoding',
17 silly get     server: 'cloudflare' } ]
18 verbose get saving raneto to /root/.npm/registry.npmjs.org/raneto/latest/.cache.json
19 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
20 silly bugs url https://github.com/gilbitron/Raneto/issues
21 verbose stack Error: spawn ENOENT
21 verbose stack     at errnoException (child_process.js:1011:11)
21 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
22 verbose cwd /volume1/web/raneto
23 error Linux 3.10.105
24 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "bugs" "raneto"
25 error node v0.10.48
26 error npm  v2.15.1
27 error code ENOENT
28 error errno ENOENT
29 error syscall spawn
30 error enoent spawn ENOENT
30 error enoent This is most likely not a problem with npm itself
30 error enoent and is related to npm not being able to find a file.
31 verbose exit [ 1, true ]
```

**Comment by ryanlelek** [comment]
Thank you for reporting.
It has been a while so we'll need to start from square 1 on testing.  
I have a Synology device to use for testing.

Please visit the Roadmap above for further discussion.
Closing this issue.
